from . import academic_year
from . import student
from . import teacher
from . import attendance
from . import classes
from . import exam
from . import subject
from . import fee
from . import performance
from . import extracurricular_activities
